# Generated by Django 3.1 on 2020-08-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0002_auto_20200827_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iso',
            old_name='code',
            new_name='name',
        ),
    ]
