# Generated by Django 3.1 on 2020-08-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='courses',
            field=models.ManyToManyField(through='many.Membership', to='many.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(through='many.Membership', to='many.Person'),
        ),
    ]
